fio = input('Ваши фамилия, имя: ')
age = input('Ваш возраст: ')
place = input('Ваше место жительства: ')
print('Ваши фамилия, имя:', fio)
print('Ваш возраст:', age)
print('Вы живёте в городе', place)
